import type { 
  Member, 
  MembershipPlan, 
  Product, 
  CheckInRecord, 
  GymClass, 
  Trainer, 
  BodyMetric, 
  PersonalRecord, 
  WorkoutRoutine, 
  EquipmentItem, 
  CashShift, 
  Sale 
} from '../types/gym';

export const INITIAL_PLANS: MembershipPlan[] = [
  {
    id: 'plan-1',
    name: 'Day Pass',
    type: 'day_pass',
    price: 15,
    durationDays: 1,
    description: 'Single full-day access to gym facilities, lockers, and showers.',
    features: ['Full Gym Floor Access', 'Locker & Sauna Access', 'Valid for 24 Hours'],
  },
  {
    id: 'plan-2',
    name: '1-Month Unlimited',
    type: 'monthly',
    price: 65,
    durationDays: 30,
    popular: true,
    description: 'Our most flexible monthly membership for dedicated fitness lovers.',
    features: ['24/7 Access Badge', 'All Group Classes Included', 'Free Fitness Assessment', '1 Guest Pass / Mo'],
  },
  {
    id: 'plan-3',
    name: '3-Month Warrior',
    type: 'quarterly',
    price: 175,
    durationDays: 90,
    description: 'Quarterly commitment with significant savings and 2 free PT sessions.',
    features: ['24/7 Access Badge', 'All Group Classes Included', '2 Complimentary PT Sessions', '10% Pro Shop Discount'],
  },
  {
    id: 'plan-4',
    name: '1-Year VIP Elite',
    type: 'annual',
    price: 599,
    durationDays: 365,
    description: 'The ultimate VIP pass for serious athletes. Includes sauna and towel service.',
    features: ['24/7 Priority Access', 'Unlimited Group Classes', '5 Complimentary PT Sessions', 'Daily Fresh Towel Service', '20% Pro Shop Discount'],
  },
  {
    id: 'plan-5',
    name: '10-Class Punch Card',
    type: 'punch_card',
    price: 120,
    durationDays: 180,
    visitLimit: 10,
    description: 'Ideal for busy professionals who want class flexibility without contract.',
    features: ['Valid for any Studio Class', '6-Month Expiration', 'Shareable with 1 Partner'],
  },
  {
    id: 'plan-6',
    name: 'Student Pass',
    type: 'monthly',
    price: 45,
    durationDays: 30,
    description: 'Discounted monthly membership with valid university or high school ID.',
    features: ['Off-Peak Access (6am-4pm)', 'Locker & Shower Access', 'Student Community Events'],
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem-1',
    memberCode: 'AF-1001',
    fullName: 'Alexander Wright',
    email: 'alex.wright@example.com',
    phone: '+1 (555) 234-5678',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Sarah Wright (Wife)',
    emergencyPhone: '+1 (555) 234-9999',
    gender: 'male',
    joinDate: '2025-06-15',
    tierId: 'plan-4',
    tierName: '1-Year VIP Elite',
    status: 'active',
    expiryDate: '2027-06-15',
    lastVisitDate: '2026-09-20T08:15:00Z',
    totalVisits: 142,
    remainingPTSessions: 3,
    waiverSigned: true,
    notes: 'VIP founding member. Prefers early morning training. Pre-ordered new belt.',
  },
  {
    id: 'mem-2',
    memberCode: 'AF-1002',
    fullName: 'Sophia Chen',
    email: 'sophia.chen@example.com',
    phone: '+1 (555) 345-6789',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'David Chen (Brother)',
    emergencyPhone: '+1 (555) 345-0000',
    gender: 'female',
    joinDate: '2026-01-10',
    tierId: 'plan-2',
    tierName: '1-Month Unlimited',
    status: 'active',
    expiryDate: '2026-10-10',
    lastVisitDate: '2026-09-20T07:45:00Z',
    totalVisits: 64,
    remainingPTSessions: 1,
    waiverSigned: true,
    notes: 'Powerlifting enthusiast. Working toward 120kg squat milestone.',
  },
  {
    id: 'mem-3',
    memberCode: 'AF-1003',
    fullName: 'Marcus Sterling',
    email: 'marcus.s@example.com',
    phone: '+1 (555) 456-7890',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Clara Sterling (Spouse)',
    emergencyPhone: '+1 (555) 456-1111',
    gender: 'male',
    joinDate: '2025-09-01',
    tierId: 'plan-3',
    tierName: '3-Month Warrior',
    status: 'expiring',
    expiryDate: '2026-09-23', // Expiring in 3 days!
    lastVisitDate: '2026-09-19T17:30:00Z',
    totalVisits: 88,
    remainingPTSessions: 0,
    waiverSigned: true,
    notes: 'Membership expires in 3 days. Send renewal reminder with warrior tier discount.',
  },
  {
    id: 'mem-4',
    memberCode: 'AF-1004',
    fullName: 'Liam O\'Connor',
    email: 'liam.oc@example.com',
    phone: '+1 (555) 567-8901',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Patrick O\'Connor (Father)',
    emergencyPhone: '+1 (555) 567-2222',
    gender: 'male',
    joinDate: '2026-04-12',
    tierId: 'plan-2',
    tierName: '1-Month Unlimited',
    status: 'expired',
    expiryDate: '2026-09-12', // Expired 8 days ago
    lastVisitDate: '2026-09-11T19:10:00Z',
    totalVisits: 31,
    remainingPTSessions: 0,
    waiverSigned: true,
    notes: 'Expired! Prompt cashier to renew upon check-in attempt.',
  },
  {
    id: 'mem-5',
    memberCode: 'AF-1005',
    fullName: 'Jessica Miller',
    email: 'jess.m@example.com',
    phone: '+1 (555) 678-9012',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Robert Miller',
    emergencyPhone: '+1 (555) 678-3333',
    gender: 'female',
    joinDate: '2026-02-20',
    tierId: 'plan-2',
    tierName: '1-Month Unlimited',
    status: 'active',
    expiryDate: '2026-11-20',
    lastVisitDate: '2026-09-02T18:00:00Z', // 18 days ago -> At-Risk!
    totalVisits: 22,
    remainingPTSessions: 2,
    waiverSigned: true,
    notes: 'At-risk churn alert: Has not visited in over 14 days. Staff reached out via WhatsApp.',
  },
  {
    id: 'mem-6',
    memberCode: 'AF-1006',
    fullName: 'Dante Rodriguez',
    email: 'dante.rod@example.com',
    phone: '+1 (555) 789-0123',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Maria Rodriguez',
    emergencyPhone: '+1 (555) 789-4444',
    gender: 'male',
    joinDate: '2025-11-15',
    tierId: 'plan-4',
    tierName: '1-Year VIP Elite',
    status: 'active',
    expiryDate: '2026-11-15',
    lastVisitDate: '2026-09-20T09:00:00Z',
    totalVisits: 110,
    remainingPTSessions: 5,
    waiverSigned: true,
    notes: 'CrossFit competitor. Trains 5x weekly.',
  },
  {
    id: 'mem-7',
    memberCode: 'AF-1007',
    fullName: 'Maya Patel',
    email: 'maya.patel@example.com',
    phone: '+1 (555) 890-1234',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Anand Patel',
    emergencyPhone: '+1 (555) 890-5555',
    gender: 'female',
    joinDate: '2026-05-01',
    tierId: 'plan-5',
    tierName: '10-Class Punch Card',
    status: 'active',
    expiryDate: '2026-11-01',
    lastVisitDate: '2026-09-18T10:00:00Z',
    totalVisits: 6,
    remainingPTSessions: 0,
    waiverSigned: true,
    notes: 'Enjoys Spin and Power Yoga sessions.',
  },
  {
    id: 'mem-8',
    memberCode: 'AF-1008',
    fullName: 'Ethan Walker',
    email: 'ethan.w@example.com',
    phone: '+1 (555) 901-2345',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    emergencyContact: 'Laura Walker',
    emergencyPhone: '+1 (555) 901-6666',
    gender: 'male',
    joinDate: '2026-07-01',
    tierId: 'plan-6',
    tierName: 'Student Pass',
    status: 'active',
    expiryDate: '2026-10-01',
    lastVisitDate: '2026-09-20T08:50:00Z',
    totalVisits: 19,
    remainingPTSessions: 0,
    waiverSigned: true,
    notes: 'State University Student. Verified valid ID.',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Gold Standard 100% Whey (Double Rich Chocolate 2.2kg)',
    category: 'supplement',
    price: 74.99,
    costPrice: 48.00,
    stock: 24,
    sku: 'SUP-WHEY-DRC',
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-2',
    name: 'Creapure Micronized Creatine 300g',
    category: 'supplement',
    price: 29.99,
    costPrice: 16.50,
    stock: 35,
    sku: 'SUP-CREA-300',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-3',
    name: 'Vortex Pre-Workout (Sour Blue Razz 40 Servings)',
    category: 'supplement',
    price: 42.50,
    costPrice: 22.00,
    stock: 18,
    sku: 'SUP-PRE-SBR',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-4',
    name: 'Celsius Sparkling Energy (Arctic Vibe 355ml)',
    category: 'beverage',
    price: 3.75,
    costPrice: 1.80,
    stock: 48,
    sku: 'BEV-CEL-AV',
    imageUrl: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-5',
    name: 'Cold Pressed Recovery Juice (Green Detox 500ml)',
    category: 'beverage',
    price: 5.50,
    costPrice: 2.75,
    stock: 14,
    sku: 'BEV-JUICE-GRN',
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-6',
    name: 'Electrolyte Mineral Water (1 Liter)',
    category: 'beverage',
    price: 2.50,
    costPrice: 0.80,
    stock: 75,
    sku: 'BEV-WTR-1L',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=200&auto=format&fit=crop&q=80',
    isTaxable: false,
  },
  {
    id: 'prod-7',
    name: 'ApexForge Heavy-Duty Shaker Bottle (800ml Stainless)',
    category: 'merchandise',
    price: 19.99,
    costPrice: 8.00,
    stock: 30,
    sku: 'MRC-SHK-STN',
    imageUrl: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-8',
    name: 'ApexForge Athletic Microfiber Gym Towel',
    category: 'merchandise',
    price: 14.50,
    costPrice: 5.00,
    stock: 40,
    sku: 'MRC-TWL-BLK',
    imageUrl: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-9',
    name: 'ApexForge Padded Weightlifting Wrist Straps',
    category: 'merchandise',
    price: 16.00,
    costPrice: 6.50,
    stock: 22,
    sku: 'MRC-STRP-LIFT',
    imageUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-10',
    name: 'Barebells Protein Bar (Caramel Cashew 55g)',
    category: 'snack',
    price: 3.99,
    costPrice: 2.10,
    stock: 50,
    sku: 'SNK-BAR-CC',
    imageUrl: 'https://images.unsplash.com/photo-1622484214457-3f338d17b5f2?w=200&auto=format&fit=crop&q=80',
    isTaxable: true,
  },
  {
    id: 'prod-11',
    name: '1-on-1 Personal Training (5-Session Package)',
    category: 'pt_package',
    price: 275.00,
    costPrice: 165.00,
    stock: 999,
    sku: 'PT-PKG-5',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&auto=format&fit=crop&q=80',
    isTaxable: false,
  },
  {
    id: 'prod-12',
    name: '1-on-1 Personal Training (10-Session Package)',
    category: 'pt_package',
    price: 500.00,
    costPrice: 300.00,
    stock: 999,
    sku: 'PT-PKG-10',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&auto=format&fit=crop&q=80',
    isTaxable: false,
  },
  {
    id: 'prod-13',
    name: 'Walk-In Day Pass Access',
    category: 'membership',
    price: 15.00,
    costPrice: 0.00,
    stock: 999,
    sku: 'MEM-DAY-PASS',
    planId: 'plan-1',
    isTaxable: false,
  },
  {
    id: 'prod-14',
    name: '1-Month Unlimited Membership Renewal',
    category: 'membership',
    price: 65.00,
    costPrice: 0.00,
    stock: 999,
    sku: 'MEM-1MO-UNL',
    planId: 'plan-2',
    isTaxable: false,
  },
  {
    id: 'prod-15',
    name: '3-Month Warrior Membership Renewal',
    category: 'membership',
    price: 175.00,
    costPrice: 0.00,
    stock: 999,
    sku: 'MEM-3MO-WAR',
    planId: 'plan-3',
    isTaxable: false,
  },
];

export const INITIAL_CHECKINS: CheckInRecord[] = [
  {
    id: 'chk-1',
    memberId: 'mem-1',
    memberName: 'Alexander Wright',
    memberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    tierName: '1-Year VIP Elite',
    timestamp: '2026-09-20T08:15:00Z',
    type: 'entry',
    status: 'granted',
  },
  {
    id: 'chk-2',
    memberId: 'mem-2',
    memberName: 'Sophia Chen',
    memberAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    tierName: '1-Month Unlimited',
    timestamp: '2026-09-20T07:45:00Z',
    type: 'entry',
    status: 'granted',
  },
  {
    id: 'chk-3',
    memberId: 'mem-6',
    memberName: 'Dante Rodriguez',
    memberAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    tierName: '1-Year VIP Elite',
    timestamp: '2026-09-20T09:00:00Z',
    type: 'entry',
    status: 'granted',
  },
  {
    id: 'chk-4',
    memberId: 'mem-8',
    memberName: 'Ethan Walker',
    memberAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    tierName: 'Student Pass',
    timestamp: '2026-09-20T08:50:00Z',
    type: 'entry',
    status: 'granted',
  },
  {
    id: 'chk-5',
    memberId: 'mem-4',
    memberName: 'Liam O\'Connor',
    memberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    tierName: '1-Month Unlimited',
    timestamp: '2026-09-20T09:12:00Z',
    type: 'entry',
    status: 'denied',
    denialReason: 'Membership expired on 2026-09-12. Renewal required.',
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'trn-1',
    name: 'Marcus Vance',
    specialty: 'Powerlifting & Hypertrophy',
    bio: 'CSCS certified with 8 years of elite strength coaching. Former collegiate powerlifter.',
    avatarUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&auto=format&fit=crop&q=80',
    rating: 4.95,
    activeClientsCount: 14,
    hourlyRate: 65,
    commissionRatePercent: 70,
    availableHours: '06:00 - 15:00',
  },
  {
    id: 'trn-2',
    name: 'Elena Rostova',
    specialty: 'Mobility, Olympic Lifting & HIIT',
    bio: 'USAW Level 2 Coach specializing in explosive power, snatch technique, and functional recovery.',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    rating: 4.98,
    activeClientsCount: 16,
    hourlyRate: 70,
    commissionRatePercent: 70,
    availableHours: '08:00 - 18:00',
  },
  {
    id: 'trn-3',
    name: 'Kai Tanaka',
    specialty: 'Calisthenics & Athletic Conditioning',
    bio: 'Focuses on core stability, bodyweight mastery, agility drills, and injury prevention.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    rating: 4.92,
    activeClientsCount: 11,
    hourlyRate: 60,
    commissionRatePercent: 65,
    availableHours: '10:00 - 20:00',
  },
];

export const INITIAL_CLASSES: GymClass[] = [
  {
    id: 'cls-1',
    title: 'CrossFit WOD & Barbells',
    instructorName: 'Elena Rostova',
    instructorAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    category: 'crossfit',
    dayOfWeek: 1, // Monday
    startTime: '07:00',
    endTime: '08:00',
    maxCapacity: 16,
    enrolledMemberIds: ['mem-1', 'mem-6', 'mem-2'],
    locationRoom: 'Arena Zone B',
    intensity: 'Extreme',
  },
  {
    id: 'cls-2',
    title: 'Power Flow Yoga & Mobility',
    instructorName: 'Sarah Jenkins',
    instructorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    category: 'yoga',
    dayOfWeek: 1,
    startTime: '08:30',
    endTime: '09:30',
    maxCapacity: 20,
    enrolledMemberIds: ['mem-7', 'mem-5'],
    locationRoom: 'Zen Studio 1',
    intensity: 'Low',
  },
  {
    id: 'cls-3',
    title: 'High-RPM Spin Cycle',
    instructorName: 'Kai Tanaka',
    instructorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    category: 'spin',
    dayOfWeek: 1,
    startTime: '17:30',
    endTime: '18:30',
    maxCapacity: 22,
    enrolledMemberIds: ['mem-2', 'mem-7', 'mem-8'],
    locationRoom: 'Cycle Theater',
    intensity: 'High',
  },
  {
    id: 'cls-4',
    title: 'Apex HIIT MetCon',
    instructorName: 'Marcus Vance',
    instructorAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&auto=format&fit=crop&q=80',
    category: 'hiit',
    dayOfWeek: 2, // Tuesday
    startTime: '18:00',
    endTime: '19:00',
    maxCapacity: 18,
    enrolledMemberIds: ['mem-1', 'mem-3', 'mem-6'],
    locationRoom: 'Functional Turf',
    intensity: 'Extreme',
  },
  {
    id: 'cls-5',
    title: 'Boxing Fight Conditioning',
    instructorName: 'Kai Tanaka',
    instructorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    category: 'boxing',
    dayOfWeek: 3, // Wednesday
    startTime: '19:00',
    endTime: '20:00',
    maxCapacity: 14,
    enrolledMemberIds: ['mem-6', 'mem-8'],
    locationRoom: 'Combat Ring',
    intensity: 'High',
  },
];

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'Matrix Commercial Treadmill T7xe #1',
    category: 'Cardio',
    serialNumber: 'MTX-TM-2024-001',
    locationFloor: 'Cardio Deck (Floor 2)',
    purchaseDate: '2024-03-15',
    condition: 'operational',
    lastServiceDate: '2026-08-10',
    nextServiceDueDate: '2026-11-10',
    notes: 'Belt lubricated and calibrated during last quarterly check.',
  },
  {
    id: 'eq-2',
    name: 'Matrix Commercial Treadmill T7xe #2',
    category: 'Cardio',
    serialNumber: 'MTX-TM-2024-002',
    locationFloor: 'Cardio Deck (Floor 2)',
    purchaseDate: '2024-03-15',
    condition: 'maintenance_due',
    lastServiceDate: '2026-05-12',
    nextServiceDueDate: '2026-09-15',
    notes: 'Incline motor making slight squeak. Service technician scheduled for Friday.',
  },
  {
    id: 'eq-3',
    name: 'Eleiko Olympic Power Cage & Platform #1',
    category: 'Free Weights',
    serialNumber: 'ELK-PWR-101',
    locationFloor: 'Ground Floor Weight Room',
    purchaseDate: '2024-01-20',
    condition: 'operational',
    lastServiceDate: '2026-07-01',
    nextServiceDueDate: '2027-01-01',
    notes: 'Includes Eleiko IWF 20kg competition bar.',
  },
  {
    id: 'eq-4',
    name: 'Nautilus Dual Adjustable Pulley / Cable Crossover',
    category: 'Strength Machines',
    serialNumber: 'NTL-CBL-404',
    locationFloor: 'Ground Floor Cable Zone',
    purchaseDate: '2024-02-10',
    condition: 'operational',
    lastServiceDate: '2026-08-22',
    nextServiceDueDate: '2026-11-22',
    notes: 'Both cable sleeves replaced with steel core aircraft wire.',
  },
  {
    id: 'eq-5',
    name: 'Clearlight Sanctuary Cedar Infrared Sauna (4-Person)',
    category: 'Facility & Saunas',
    serialNumber: 'CLR-IR-900',
    locationFloor: 'Recovery Lounge & Locker Zone',
    purchaseDate: '2024-06-01',
    condition: 'operational',
    lastServiceDate: '2026-09-01',
    nextServiceDueDate: '2026-12-01',
    notes: 'Full sanitization and heater element check completed.',
  },
];

export const INITIAL_PRS: PersonalRecord[] = [
  {
    id: 'pr-1',
    memberId: 'mem-1',
    exerciseName: 'Barbell Deadlift',
    weightKg: 220,
    reps: 1,
    achievedAt: '2026-09-15T09:30:00Z',
    previousRecordKg: 210,
    notes: 'Clean pull, no hitching. Chalk and belt.',
  },
  {
    id: 'pr-2',
    memberId: 'mem-1',
    exerciseName: 'Flat Barbell Bench Press',
    weightKg: 142.5,
    reps: 2,
    achievedAt: '2026-09-10T10:00:00Z',
    previousRecordKg: 140,
    notes: 'Spotted by Coach Marcus.',
  },
  {
    id: 'pr-3',
    memberId: 'mem-2',
    exerciseName: 'Back Squat',
    weightKg: 115,
    reps: 3,
    achievedAt: '2026-09-18T08:10:00Z',
    previousRecordKg: 110,
    notes: 'Hit parallel with solid depth. Lifetime PR!',
  },
  {
    id: 'pr-4',
    memberId: 'mem-6',
    exerciseName: 'Overhead Press (OHP)',
    weightKg: 85,
    reps: 1,
    achievedAt: '2026-09-12T11:00:00Z',
    previousRecordKg: 80,
    notes: 'Strict overhead press without knee dip.',
  },
];

export const INITIAL_BODY_METRICS: BodyMetric[] = [
  {
    id: 'bm-1',
    memberId: 'mem-1',
    recordedAt: '2026-07-01T08:00:00Z',
    weightKg: 88.5,
    bodyFatPercent: 17.2,
    muscleMassKg: 42.1,
    chestCm: 108,
    waistCm: 86,
    armCm: 41,
    notes: 'Baseline scan at start of summer recomp cycle.',
  },
  {
    id: 'bm-2',
    memberId: 'mem-1',
    recordedAt: '2026-08-01T08:00:00Z',
    weightKg: 87.2,
    bodyFatPercent: 15.8,
    muscleMassKg: 42.6,
    chestCm: 109,
    waistCm: 84,
    armCm: 41.5,
    notes: 'Great fat drop while preserving lean tissue.',
  },
  {
    id: 'bm-3',
    memberId: 'mem-1',
    recordedAt: '2026-09-01T08:00:00Z',
    weightKg: 86.4,
    bodyFatPercent: 14.3,
    muscleMassKg: 43.2,
    chestCm: 110,
    waistCm: 82.5,
    armCm: 42,
    notes: 'Current scan: visible vascularity and strong core definition.',
  },
  {
    id: 'bm-4',
    memberId: 'mem-2',
    recordedAt: '2026-08-15T08:00:00Z',
    weightKg: 62.0,
    bodyFatPercent: 21.0,
    muscleMassKg: 28.5,
    waistCm: 68,
    notes: 'Starting powerlifting prep cycle.',
  },
  {
    id: 'bm-5',
    memberId: 'mem-2',
    recordedAt: '2026-09-15T08:00:00Z',
    weightKg: 63.2,
    bodyFatPercent: 20.4,
    muscleMassKg: 29.4,
    waistCm: 68.5,
    notes: 'Clean lean mass gain with increased squat numbers.',
  },
];

export const INITIAL_ROUTINES: WorkoutRoutine[] = [
  {
    id: 'rtn-1',
    memberId: 'mem-1',
    title: 'Hypertrophy Heavy - Push Day A',
    splitType: 'Push',
    updatedAt: '2026-09-14',
    exercises: [
      { id: 'ex-1', name: 'Incline Dumbbell Press', targetSets: 4, targetReps: '8-10', targetWeightKg: 36, restSeconds: 90, notes: 'Focus on 3-second eccentric stretch.' },
      { id: 'ex-2', name: 'Barbell Overhead Press', targetSets: 4, targetReps: '6-8', targetWeightKg: 70, restSeconds: 120, notes: 'Strict lockouts overhead.' },
      { id: 'ex-3', name: 'Cable Lateral Raise', targetSets: 3, targetReps: '12-15', targetWeightKg: 12, restSeconds: 60, notes: 'Constant tension at top position.' },
      { id: 'ex-4', name: 'Dips (Weighted)', targetSets: 3, targetReps: '10', targetWeightKg: 20, restSeconds: 90, notes: 'Attach plate with dipping belt.' },
      { id: 'ex-5', name: 'Overhead Tricep Rope Extension', targetSets: 3, targetReps: '12-15', targetWeightKg: 28, restSeconds: 60, notes: 'Flare rope out at full extension.' },
    ],
  },
  {
    id: 'rtn-2',
    memberId: 'mem-1',
    title: 'Deadlift & Posterior Chain - Pull Day A',
    splitType: 'Pull',
    updatedAt: '2026-09-12',
    exercises: [
      { id: 'ex-6', name: 'Conventional Deadlift', targetSets: 4, targetReps: '3-5', targetWeightKg: 190, restSeconds: 180, notes: 'Reset each repetition on the floor.' },
      { id: 'ex-7', name: 'Chest-Supported T-Bar Row', targetSets: 4, targetReps: '8-10', targetWeightKg: 65, restSeconds: 90, notes: 'Squeeze scapulae together at peak.' },
      { id: 'ex-8', name: 'Neutral Grip Lat Pulldown', targetSets: 3, targetReps: '10-12', targetWeightKg: 75, restSeconds: 75, notes: 'Pull down to upper collarbone.' },
      { id: 'ex-9', name: 'Incline Dumbbell Bicep Curls', targetSets: 3, targetReps: '10-12', targetWeightKg: 16, restSeconds: 60, notes: 'Full elbow extension at bottom.' },
    ],
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1',
    invoiceNo: 'INV-2026-0038',
    customerName: 'Alexander Wright',
    memberId: 'mem-1',
    items: [
      { productId: 'prod-1', productName: 'Gold Standard 100% Whey (Double Rich Chocolate 2.2kg)', category: 'supplement', unitPrice: 74.99, quantity: 1, total: 74.99 },
      { productId: 'prod-7', productName: 'ApexForge Heavy-Duty Shaker Bottle (800ml Stainless)', category: 'merchandise', unitPrice: 19.99, quantity: 1, total: 19.99 },
    ],
    subtotal: 94.98,
    tax: 7.60,
    discount: 0,
    total: 102.58,
    paymentMethod: 'card',
    cashierName: 'Front Desk Admin',
    timestamp: '2026-09-20T08:25:00Z',
    status: 'completed',
  },
  {
    id: 'sale-2',
    invoiceNo: 'INV-2026-0039',
    customerName: 'Dante Rodriguez',
    memberId: 'mem-6',
    items: [
      { productId: 'prod-4', productName: 'Celsius Sparkling Energy (Arctic Vibe 355ml)', category: 'beverage', unitPrice: 3.75, quantity: 2, total: 7.50 },
      { productId: 'prod-10', productName: 'Barebells Protein Bar (Caramel Cashew 55g)', category: 'snack', unitPrice: 3.99, quantity: 2, total: 7.98 },
    ],
    subtotal: 15.48,
    tax: 1.24,
    discount: 0,
    total: 16.72,
    paymentMethod: 'qris',
    cashierName: 'Front Desk Admin',
    timestamp: '2026-09-20T09:05:00Z',
    status: 'completed',
  },
  {
    id: 'sale-3',
    invoiceNo: 'INV-2026-0040',
    customerName: 'Ethan Walker',
    memberId: 'mem-8',
    items: [
      { productId: 'prod-6', productName: 'Electrolyte Mineral Water (1 Liter)', category: 'beverage', unitPrice: 2.50, quantity: 1, total: 2.50 },
    ],
    subtotal: 2.50,
    tax: 0,
    discount: 0,
    total: 2.50,
    paymentMethod: 'cash',
    cashReceived: 5.00,
    changeGiven: 2.50,
    cashierName: 'Front Desk Admin',
    timestamp: '2026-09-20T09:15:00Z',
    status: 'completed',
  },
];

export const INITIAL_SHIFT: CashShift = {
  id: 'shift-today',
  cashierName: 'Front Desk Admin',
  startTime: '2026-09-20T06:00:00Z',
  openingFloat: 200.00,
  expectedCash: 202.50, // opening $200 + $2.50 cash sale
  status: 'open',
  notes: 'Morning shift active. Till balanced at start.',
};
